revert previous merge: bouncycastle 1.62 to 1.67.
It causes an runtime error as:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'boolean org.bouncycastle.asn1.ASN1ObjectIdentifier.equals(org.bouncycastle.asn1.ASN1Primitive)'
	at org.fsij.pdftimestamp.CertInformationHelper.getAuthorityInfoExtensionValue(CertInformationHelper.java:89)
	at org.fsij.pdftimestamp.CertInformationCollector.traverseChain(CertInformationCollector.java:230)
	at org.fsij.pdftimestamp.CertInformationCollector.processSignerStore(CertInformationCollector.java:206)
	at org.fsij.pdftimestamp.CertInformationCollector.getCertInfo(CertInformationCollector.java:120)
	at org.fsij.pdftimestamp.CertInformationCollector.getLastCertInfo(CertInformationCollector.java:96)
	at org.fsij.pdftimestamp.AddValidationInformation.doValidation(AddValidationInformation.java:127)
	at org.fsij.pdftimestamp.AddValidationInformation.validateSignature(AddValidationInformation.java:105)
	at org.fsij.pdftimestamp.PDFTimeStamp.addLTV(PDFTimeStamp.java:85)
	at org.fsij.pdftimestamp.PDFTimeStamp.main(PDFTimeStamp.java:72)
```